import { CommentItem, CreatorChannel, RelatedVideo, UserProfile, VideoPreset } from '../types';

export const CREATOR_CHANNELS: Record<string, CreatorChannel> = {
  'Rick Astley': {
    id: 'rick_astley',
    name: 'Rick Astley',
    handle: '@RickAstleyYT',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '425万人',
    videosCount: 142,
    joinedDate: '2007年5月10日',
    bio: 'The official YouTube channel of Rick Astley. Never Gonna Give You Up, Together Forever, and new music from the album "Are We There Yet?" out now!',
    isVerified: true,
    totalViews: '24億回',
    country: 'イギリス',
    featuredVideoId: 'dQw4w9WgXcQ',
    featuredVideoTitle: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
    featuredVideoDesc: 'The official video for “Never Gonna Give You Up” by Rick Astley. Taken from the album ‘Whenever You Need Somebody’ – deluxe 2CD and digital deluxe out now!',
    videos: [
      {
        id: 'dQw4w9WgXcQ',
        title: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
        views: '15.2億回',
        uploadedAt: '14年前',
        duration: '3:33',
        thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
      },
      {
        id: 'yPYZpwSpKmA',
        title: 'Rick Astley - Together Forever (Official Music Video)',
        views: '2.8億回',
        uploadedAt: '13年前',
        duration: '3:25',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'L_LUpnjgPso',
        title: 'Rick Astley - Never Gonna Stop (Official Video)',
        views: '450万回',
        uploadedAt: '1年前',
        duration: '3:18',
        thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80',
      },
      {
        id: 'kXYiU_JCYtU',
        title: 'Rick Astley - Cry for Help (Official Music Video)',
        views: '3200万回',
        uploadedAt: '10年前',
        duration: '4:05',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80',
      },
    ],
    communityPosts: [
      {
        id: 'p1',
        date: '3日前',
        content: 'Thank you for all the incredible support on the tour! New concert dates announced soon! 🎸✨',
        likes: 12400,
        commentsCount: 382,
      },
      {
        id: 'p2',
        date: '2週間前',
        content: 'Can you believe Never Gonna Give You Up hit another milestone? You know the rules and so do I! 😉❤️',
        likes: 45000,
        commentsCount: 1520,
      },
    ],
  },
  'Lofi Girl': {
    id: 'lofi_girl',
    name: 'Lofi Girl',
    handle: '@LofiGirl',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507842229451-7f01be7fe7ab?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '1430万人',
    videosCount: 620,
    joinedDate: '2015年3月18日',
    bio: 'Peaceful lofi hip hop / chill beats to study, relax, sleep, and work to. Welcome to our cozy 24/7 lofi universe! 🎧✨',
    isVerified: true,
    totalViews: '18億回',
    country: 'フランス',
    featuredVideoId: 'L_LUpnjgPso',
    featuredVideoTitle: 'synthwave radio 🌌 - chill / retro beats to relax, study to',
    featuredVideoDesc: 'Welcome to the Synthwave radio stream! A peaceful retro broadcast for coding, studying, and late night focus.',
    videos: [
      {
        id: 'L_LUpnjgPso',
        title: 'synthwave radio 🌌 - chill / retro beats to relax, study to',
        views: '840万回',
        uploadedAt: 'ライブ配信中',
        duration: 'LIVE',
        thumbnailUrl: 'https://img.youtube.com/vi/L_LUpnjgPso/mqdefault.jpg',
      },
      {
        id: 'jfKfPfyJRdk',
        title: 'lofi hip hop radio 📚 - beats to relax/study to',
        views: '9200万回',
        uploadedAt: 'ライブ配信中',
        duration: 'LIVE',
        thumbnailUrl: 'https://img.youtube.com/vi/jfKfPfyJRdk/mqdefault.jpg',
      },
      {
        id: '4xDzrJKXOOY',
        title: 'synthwave boy 🌃 - 1 AM Coding Session (Lofi Mix)',
        views: '1200万回',
        uploadedAt: '6か月前',
        duration: '1:02:15',
        thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&auto=format&fit=crop&q=80',
      },
    ],
    communityPosts: [
      {
        id: 'lp1',
        date: '1日前',
        content: 'New compilation vinyl dropping this Friday! What track has been your favorite for studying this semester? 📚☕',
        likes: 18900,
        commentsCount: 420,
      },
    ],
  },
  'Google Developers': {
    id: 'google_dev',
    name: 'Google Developers',
    handle: '@googledevelopers',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '235万人',
    videosCount: 5400,
    joinedDate: '2007年12月5日',
    bio: 'The Google Developers channel brings you the latest developer news, tutorials, and event livestreams including Google I/O, Web Devs, Android, Firebase and Cloud.',
    isVerified: true,
    totalViews: '2.1億回',
    country: 'アメリカ合衆国',
    featuredVideoId: 'M7lc1UVf-VE',
    featuredVideoTitle: 'YouTube Developers: Introducing the YouTube IFrame Player API',
    featuredVideoDesc: 'Learn how to embed YouTube video players in your web applications and control them with JavaScript.',
    videos: [
      {
        id: 'M7lc1UVf-VE',
        title: 'YouTube Developers: Introducing the YouTube IFrame Player API',
        views: '180万回',
        uploadedAt: '12年前',
        duration: '4:15',
        thumbnailUrl: 'https://img.youtube.com/vi/M7lc1UVf-VE/mqdefault.jpg',
      },
      {
        id: 'hT_nvWreIhg',
        title: 'Building Modern Web Apps with Google Cloud & APIs',
        views: '34万回',
        uploadedAt: '1年前',
        duration: '18:40',
        thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80',
      },
    ],
    communityPosts: [
      {
        id: 'gp1',
        date: '5日前',
        content: 'Check out the latest tools in Web AI and Client APIs. What are you building this week? 💻🚀',
        likes: 5400,
        commentsCount: 190,
      },
    ],
  },
};

export function getCreatorChannel(channelName: string, videoId?: string): CreatorChannel {
  if (CREATOR_CHANNELS[channelName]) {
    return CREATOR_CHANNELS[channelName];
  }

  // Generate dynamic authentic creator channel for any custom creator
  const safeName = channelName || 'YouTube 投稿者';
  const cleanHandle = '@' + safeName.toLowerCase().replace(/[^a-z0-9_]/g, '_').substring(0, 15);
  const currentVid = videoId || 'dQw4w9WgXcQ';

  return {
    id: `creator_${safeName}`,
    name: safeName,
    handle: cleanHandle || '@creator_channel',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '85.4万人',
    videosCount: 64,
    joinedDate: '2020年8月14日',
    bio: `${safeName} の公式チャンネルです。教育・解説・エンタメ動画をYouTube Player for Educationでも快適にお楽しみいただけます。`,
    isVerified: true,
    totalViews: '4500万回',
    country: '日本',
    featuredVideoId: currentVid,
    featuredVideoTitle: `${safeName} - 最新アップロード動画`,
    featuredVideoDesc: `${safeName} の公式動画です。YouTube Player for Educationにより安全・広告非表示で視聴できます。`,
    videos: [
      {
        id: currentVid,
        title: `${safeName} - 注目動画`,
        views: '120万回',
        uploadedAt: '2日前',
        duration: '4:15',
        thumbnailUrl: `https://img.youtube.com/vi/${currentVid}/mqdefault.jpg`,
      },
      {
        id: 'L_LUpnjgPso',
        title: `${safeName} - 集中・学習用 BGM`,
        views: '840万回',
        uploadedAt: '1か月前',
        duration: 'LIVE',
        thumbnailUrl: 'https://img.youtube.com/vi/L_LUpnjgPso/mqdefault.jpg',
      },
      {
        id: 'dQw4w9WgXcQ',
        title: `${safeName} - 人気のハイライト`,
        views: '15億回',
        uploadedAt: '1年前',
        duration: '3:33',
        thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
      },
    ],
    communityPosts: [
      {
        id: 'cp_dynamic',
        date: '2日前',
        content: `いつもご視聴ありがとうございます！${safeName}の最新動画を公開しました。ぜひEducationプレイヤーでもご覧ください！`,
        likes: 1240,
        commentsCount: 45,
      },
    ],
  };
}

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: 'user_main',
    name: 'YouTubebate ユーザー',
    handle: '@youtubebate_official',
    email: 'user@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '1.24万',
    videosCount: 48,
    joinedDate: '2023年4月15日',
    bio: 'YouTube Player for Education 活用中。広告なし・集中環境で学習動画を配信しています。',
    isVerified: true,
  },
  {
    id: 'user_student',
    name: '田中 健太 (学習用アカウント)',
    handle: '@kenta_study',
    email: 'kenta.study@school.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507842229451-7f01be7fe7ab?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '320',
    videosCount: 5,
    joinedDate: '2024年1月10日',
    bio: 'プログラミングと数学の動画を整理中 📚',
    isVerified: false,
  },
  {
    id: 'user_creator',
    name: 'TechLab Japan',
    handle: '@techlab_jp',
    email: 'contact@techlab.jp',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
    subscriberCount: '28.5万',
    videosCount: 215,
    joinedDate: '2021年9月20日',
    bio: 'Webテクノロジー・GAS・フロントエンド開発の解説チャンネル。',
    isVerified: true,
  },
];

export const INITIAL_RELATED_VIDEOS: RelatedVideo[] = [
  {
    id: 'dQw4w9WgXcQ',
    title: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
    channelTitle: 'Rick Astley',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    viewCount: '15億回',
    publishedAt: '14年前',
    duration: '3:33',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    category: '音楽',
  },
  {
    id: 'L_LUpnjgPso',
    title: 'synthwave radio 🌌 - chill / retro beats to relax, study to',
    channelTitle: 'Lofi Girl',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    viewCount: '840万回',
    publishedAt: '2年前',
    duration: 'LIVE',
    thumbnailUrl: 'https://img.youtube.com/vi/L_LUpnjgPso/mqdefault.jpg',
    category: '勉強用',
  },
  {
    id: 'M7lc1UVf-VE',
    title: 'YouTube Developers: Introducing the YouTube IFrame Player API',
    channelTitle: 'Google Developers',
    channelAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    viewCount: '180万回',
    publishedAt: '12年前',
    duration: '4:15',
    thumbnailUrl: 'https://img.youtube.com/vi/M7lc1UVf-VE/mqdefault.jpg',
    category: '開発・技術',
  },
  {
    id: 'jfKfPfyJRdk',
    title: 'lofi hip hop radio 📚 - beats to relax/study to',
    channelTitle: 'Lofi Girl',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    viewCount: '9200万回',
    publishedAt: '1年前',
    duration: 'LIVE',
    thumbnailUrl: 'https://img.youtube.com/vi/jfKfPfyJRdk/mqdefault.jpg',
    category: '勉強用',
  },
  {
    id: 'kXYiU_JCYtU',
    title: 'Linkin Park - Numb (Official Music Video) [4K Upgrade]',
    channelTitle: 'Linkin Park',
    channelAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
    viewCount: '22億回',
    publishedAt: '16年前',
    duration: '3:07',
    thumbnailUrl: 'https://img.youtube.com/vi/kXYiU_JCYtU/mqdefault.jpg',
    category: '音楽',
  },
  {
    id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    channelTitle: 'Luis Fonsi',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    viewCount: '84億回',
    publishedAt: '7年前',
    duration: '4:42',
    thumbnailUrl: 'https://img.youtube.com/vi/kJQP7kiw5Fk/mqdefault.jpg',
    category: '音楽',
  },
  {
    id: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE (강남スタイル) M/V',
    channelTitle: 'officialpsy',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    viewCount: '51億回',
    publishedAt: '11年前',
    duration: '4:13',
    thumbnailUrl: 'https://img.youtube.com/vi/9bZkp7q19f0/mqdefault.jpg',
    category: '音楽',
  },
  {
    id: 'fJ9rUzIMcZQ',
    title: 'Queen - Bohemian Rhapsody (Official Video Remastered)',
    channelTitle: 'Queen Official',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    viewCount: '17億回',
    publishedAt: '15年前',
    duration: '5:59',
    thumbnailUrl: 'https://img.youtube.com/vi/fJ9rUzIMcZQ/mqdefault.jpg',
    category: '名曲',
  },
];

export const INITIAL_COMMENTS: CommentItem[] = [
  {
    id: 'c1',
    videoId: 'dQw4w9WgXcQ',
    authorName: 'YouTube Education Fan',
    authorHandle: '@edu_master_jp',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    text: 'YouTubebate版のおかげで、スプレッドシートの動的パラメータを反映しながら広告なしのEducationプレイヤーで快適に視聴できます！最高です！🔥',
    timestamp: '2日前',
    likes: 1420,
    isLiked: false,
    isHeartedByCreator: true,
    totalRepliesCount: 5,
    replies: [
      {
        id: 'r1_1',
        authorName: 'しあTube開発者',
        authorHandle: '@shia_tube_dev',
        authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
        text: 'ご活用いただきありがとうございます！スプレッドシートA1セルのリアルタイム更新にも完全対応しています！✨',
        timestamp: '1日前',
        likes: 312,
        isOwner: true,
      },
      {
        id: 'r1_2',
        authorName: 'Webエンジニア佐藤',
        authorHandle: '@sato_dev',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        text: 'GASでもcode.gsとindex.htmlだけで簡単にデプロイできるのが本当に便利ですね。学校や社内での導入にもピッタリです。',
        timestamp: '18時間前',
        likes: 85,
      },
      {
        id: 'r1_3',
        authorName: '学生プログラマー',
        authorHandle: '@student_coder',
        authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
        text: '別タブで開く機能も重宝してます！',
        timestamp: '10時間前',
        likes: 29,
      },
    ],
  },
  {
    id: 'c2',
    videoId: 'dQw4w9WgXcQ',
    authorName: 'Classic Rock Records',
    authorHandle: '@classic_music_lover',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    text: '何度聴いても色褪せない名曲。Educationプレイヤーで見ると余計なポップアップがなくて曲に没頭できるのが素晴らしい。',
    timestamp: '5日前',
    likes: 893,
    isLiked: false,
    totalRepliesCount: 3,
    replies: [
      {
        id: 'r2_1',
        authorName: '80s Disco Fan',
        authorHandle: '@80s_disco',
        authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80',
        text: '2026年になっても伝説のリックロールですね笑',
        timestamp: '3日前',
        likes: 198,
      },
    ],
  },
];
